# LOOPS
from logging import exception


while(cond):
    
else:
    # everytime after looop finishes running 

# break, continue, pass

for cond in range():
    #in is imp
else:

# break, continue, pass
#FUNCTIONS

def function(parameters)#function-def

function(values-arguments) #passing values, ref
#arbitary, keyword arguments

try:
    print("hi")
except:
    print("nth hapnd")
else:
    print("wassup")
finally:
    print("doesn't care")

x=0
if x==0:
    raise Exception("sha")